version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/html
        container_name: flagsmith_nginx
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        depends_on:
            - app

    app:
        build: 
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        working_dir: /var/www/html
        container_name: flagsmith_laravel_project
        restart: unless-stopped
        tty: true
        volumes:
            - '.:/var/www/html'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
            - './docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf'
            - './docker/php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
